
VIDEO_SCRIPT_JSON_OUTPUT = """
        json_schema2 = {
            "name": "format_video_script",
            "description": "Formats to a 30-45sec video script.",
            "type": "object",
            "properties": {
            "list_of_scenes": {
                "type": "array",
                "description": "List of scenes for video script, there should be at least 6 scenes or more",
                "items": {
                "type": "object",
                "properties": {
                    "scene": {
                    "type": "string",
                    "description": "Scene description for video should be visual and general and not include the name of the user to describe what is said in the subtitles. Max 5 words\nExample: family trip skiing | accident bike crash"
                    },
                    "subtitles": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "description": "video subtitles script for video which needs to be coherent and should be funny and sarcastic but informative"
                    }
                    }
                },
                "required": ["scene", "subtitles"]
                }
            }
            },
            "required": ["list_of_scenes"]
        }
"""

VIDEO_SCRIPT_PROMPT = """Goal:Generate a detailed 30-45sec video script to generate a video to engage with a customer needs.\n\n
RULES:
1. Video script must be based on the "Custom knowledge base:" and "User query"
2. Video Script must comprise of a) Video Script voice over text, b) Visual background video descriptions
3. Length of video script must be 30-45sec, 6 scenes or more, cannot be too short
4. Format the video script to JSON object with list_of_scenes, scenes and subtitles
5. Curate the POV to be watched from the perspective of the customer (1st person)
6. Style of video script should be funny and sarcastic but informative
7. Video Script must have a flow and make sense
8. The Video Script does not need to introduce the customer details at the start, just say "Hi <customer name>" and start the video script
9. "Scene" must be max 5words, cannot have specific names, must be generic. Example:family trip skiing | accident bike crash
10. Video script as much as possible to include specific financial product names from custom knowledge base, if any\n\n

Custom knowledge base:\n-------------------------{relevant_documents}\n---------------------------------\n\n

Strictly following the RULES: generate a video script to answer the User Query:"{query}"."""

VIDEO_SCRIPT_EVALUATOR_PROMPT = """Goal: Evaluate the video script generated by the AI\n based on the following rules:\n and provide feedback based on the following rules:\n

RULES:
1. Video script scenes are of the correct length, 30-45sec, 6 scenes or more, each scene subtitles length are sufficient
2. As you read the script, does it make sense? Is there a proper flow?
3. Does the information in the video script answer the user query?
4. Is the scene description too specific? Is it generic enough?
5. The starting of the video, does it introduce the customer details at the start, just say "Hi <customer name>" and start the video script
6. Is it watchable from the perspective of the customer (1st person), E.g saying You can purchase xxx for your xxx needs

Video_script:
{video_script}
"""

VIDEO_SCRIPT_ENHANCER_PROMPT = """Goal: Enhance the given video script generated\n based on feedback\n

RULES:
1. Video script must be based on the "Custom knowledge base:" and "User query"
2. Video Script must comprise of a) Video Script voice over text, b) Visual background video descriptions
3. Length of video script must be 30-45sec, 6 scenes or more, cannot be too short
4. Format the video script to JSON object with list_of_scences, scenes and subtitles
5. Curate the POV to be watched from the perspective of the customer (1st person), E.g You can purchase xxx for your xxx needs
6. Style of video script should be funny and sarcastic  but informative
7. Video Script must have a flow and make sense
8. The Video Script does not need to introduce the customer details at the start, just say "Hi <customer name>" and start the video script
9. "Scene" must be max 5words, cannot have specific names, must be generic. Example:family trip skiing | accident bike crash
10. Video script as much as possible to include specific financial product names from custom knowledge base, if any\n\n

Old Video Script:
{old_video_script}

Feedback:
{feedback}

Original User Query:
{query}
"""


PINECONE_QUERY_FORMATTER = """Role: Help insurance customers figure out what's the best product to purchase given their needs. Product information are stored in PDFs of documents and the goal is to extract most\n
  Given the following user prompt, formulate a paragraph depicting what would be the most relevant to provide the user with an answer from a knowledge base.
    You should follow the following rules when generating and answer:
    - You should remove any punctuation from the question
    - You should remove any words that are not relevant to the question
    - If you are unable to formulate a question, respond with the same USER PROMPT you got.

    USER PROMPT: {userPrompt}

    CONVERSATION LOG: {conversationHistory}

    Final answer:
    `
"""

RELEVANT_DOCUMENT_FILTER_PROMPT="""Goal: Identify relevant text information based on the following rules:\n
1. Text must have some relevancy information that can help answering the user query
2. Your final answer does not have to answer the use query. You just have to answer identify relevant text information that can help answering the user query, if any.
3. Relevant output information to answer user context should be very exhaustive, as much as possible, ~1500 words
4. You do not have to explain any reasoning for your answer, just provide the relevant text information that can help answering the user query immediately
Ask yourself, "Does this document contain information that would help answer the query? "

Documents:
{documents}

Return All relevant information as much as possible that could potentially help answer: {userPrompt} 
"""

PDF_CONTEXT_SUMMARIZER_PROMPT = """Goal: Read the PDF information,understand it and summarize the pdf to account for specific target audience\n
Rules:
0. General summary of key information of the PDF
1. What kind of needs and concerns does this PDF address? if any
2. Who is the target audience for this PDF?, if any
3. How does it help the target audience with relation to their lifestyle/needs/concerns?
4. What specific service name does this pdf contain, if any?
5. Prime Example of a persona needs/concerns jobs that will find this PDF extremely useful, state the persona needs/concerns age and lifestyle etc.

You do not have to explicitly follow the format of the rules in your answer, based on the content of the PDF, and the rules generate text that properly encapsulates whatever key information corresponding to the rules.
PDF Information:
{pdf_information}
"""
